name: Flags & Feathers
favicon: null
layout_spectrum: 0.8906961076427251
typography_spectrum: 0.26569679751992226
title: Yum Chenmo's Stupas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5642613403033465
  lightness: 0.5864312923513353
  saturation: 0.41207186388783157
  rhythmicContrast: 0.6680185969453305
purpose: []
