name: Yum Chenmo's Stupas
favicon: null
layout_spectrum: 0.94694
typography_spectrum: 0.65058
title: Yum Chenmo's Stupas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8fd9fe'
    - '#005ea8'
    - '#28276b'
    - '#ef1e27'
    - '#c59e25'
  brandStrength: 0.4375
  lightness: 0.5864312923513353
  saturation: 0.41207186388783157
  rhythmicContrast: 0.5
purpose: []
